---
actions:
- Attainment
- Starting
- Neglect
- Fight
- Recruit
- Triumph
- Violate
- Oppose
- Malice
- Communicate
- Persecute
- Increase
- Decrease
- Abandon
- Gratify
- Inquire
- Antagonise
- Move
- Waste
- Truce
- Release
- Befriend
- Judge
- Desert
- Dominate
- Procrastinate
- Praise
- Separate
- Take
- Break
- Heal
- Delay
- Stop
- Lie
- Return
- Immitate
- Struggle
- Inform
- Bestow
- Postpone
- Expose
- Haggle
- Imprison
- Release
- Celebrate
- Develop
- Travel
- Block
- Harm
- Debase
- Overindulge
- Adjourn
- Adversity
- Kill
- Disrupt
- Usurp
- Create
- Betray
- Agree
- Abuse
- Oppress
- Inspect
- Ambush
- Spy
- Attach
- Carry
- Open
- Carelessness
- Ruin
- Extravagance
- Trick
- Arrive
- Propose
- Divide
- Refuse
- Mistrust
- Deceive
- Cruelty
- Intolerance
- Trust
- Excitement
- Activity
- Assist
- Care
- Negligence
- Passion
- Work
- Control
- Attract
- Failure
- Pursue
- Vengeance
- Proceedings
- Dispute
- Punish
- Guide
- Transform
- Overthrow
- Oppress
- Change
subjects:
- Goals
- Dreams
- Environment
- Outside
- Inside
- Reality
- Allies
- Enemies
- Evil
- Good
- Emotions
- Opposition
- War
- Peace
- The innocent
- Love
- The spiritual
- The intellectual
- New ideas
- Joy
- Messages
- Energy
- Balance
- Tension
- Friendship
- The physical
- A project
- Pleasures
- Pain
- Possessions
- Benefits
- Plans
- Lies
- Expectations
- Legal matters
- Bureaucracy
- Business
- A path
- News
- Exterior factors
- Advice
- A plot
- Competition
- Prison
- Illness
- Food
- Attention
- Success
- Failure
- Travel
- Jealousy
- Dispute
- Home
- Investment
- Suffering
- Wishes
- Tactics
- Stalemate
- Randomness
- Misfortune
- Death
- Disruption
- Power
- A burden
- Intrigues
- Fears
- Ambush
- Rumor
- Wounds
- Extravagance
- A representative
- Adversities
- Opulence
- Liberty
- Military
- The mundane
- Trials
- Masses
- Vehicle
- Art
- Victory
- Dispute
- Riches
- Status quo
- Technology
- Hope
- Magic
- Illusions
- Portals
- Danger
- Weapons
- Animals
- Weather
- Elements
- Nature
- The public
- Leadership
- Fame
- Anger
- Information
fatechart:
- - 50
  - 25
  - 10
  - 5
  - 5
  - 0
  - 0
  - -20
  - -20
  - -40
  - -40
  - -55
  - -65
- - 75
  - 50
  - 25
  - 15
  - 10
  - 5
  - 5
  - 0
  - 0
  - -20
  - -20
  - -35
  - -45
- - 90
  - 75
  - 50
  - 35
  - 25
  - 15
  - 10
  - 5
  - 5
  - 0
  - 0
  - -15
  - -25
- - 95
  - 85
  - 65
  - 50
  - 45
  - 25
  - 15
  - 10
  - 5
  - 5
  - 5
  - -5
  - -15
- - 100
  - 90
  - 75
  - 55
  - 50
  - 35
  - 20
  - 15
  - 10
  - 5
  - 5
  - 0
  - -10
- - 105
  - 95
  - 85
  - 75
  - 65
  - 50
  - 35
  - 25
  - 15
  - 10
  - 10
  - 5
  - -5
- - 110
  - 95
  - 90
  - 85
  - 80
  - 65
  - 50
  - 45
  - 25
  - 20
  - 15
  - 5
  - 0
- - 115
  - 100
  - 95
  - 90
  - 85
  - 75
  - 55
  - 50
  - 35
  - 25
  - 20
  - 10
  - 5
- - 120
  - 105
  - 95
  - 95
  - 90
  - 85
  - 75
  - 65
  - 50
  - 45
  - 35
  - 15
  - 5
- - 125
  - 115
  - 100
  - 95
  - 95
  - 90
  - 80
  - 75
  - 55
  - 50
  - 45
  - 20
  - 10
- - 130
  - 125
  - 110
  - 95
  - 95
  - 90
  - 85
  - 80
  - 65
  - 55
  - 50
  - 25
  - 10
- - 150
  - 145
  - 130
  - 100
  - 100
  - 95
  - 95
  - 90
  - 85
  - 80
  - 75
  - 50
  - 25
- - 170
  - 165
  - 150
  - 120
  - 120
  - 100
  - 100
  - 95
  - 95
  - 90
  - 90
  - 75
  - 50
